# Generated by Django 3.1.2 on 2021-01-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memedata', '0003_auto_20201104_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '测试环境主播信息表',
                'verbose_name_plural': '测试环境主播信息表',
                'db_table': 'test_star',
            },
        ),
    ]
